import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

export const metadata = {
  title: "Terms of Use — Promter",
  description: "Terms of Use for Promter.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-28 pb-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-2">
            Terms of Use
          </h1>
          <p className="text-sm text-white/30 mb-10">Last updated: March 19, 2026</p>

          <div className="space-y-8 text-sm text-white/50 leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using Promter at promter.dev (the &quot;Service&quot;), you agree to be bound
                by these Terms of Use. If you do not agree to these terms, please do not use the
                Service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
              <p>
                Promter is a free, open-source prompt library and generator for building websites
                with AI coding assistants. The Service provides modular prompt modules, templates,
                and an AI-powered prompt builder that runs entirely in your browser.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. Use of Generated Content</h2>
              <ul className="list-disc list-inside space-y-2 text-white/40">
                <li>
                  All prompts and templates provided by the Service are released under the{" "}
                  <span className="text-white/50 font-medium">MIT License</span>. You are free to use,
                  modify, and distribute them for any purpose, including commercial use.
                </li>
                <li>
                  Websites and code generated by AI assistants using our prompts are your own. We
                  claim no ownership over any output produced by third-party AI tools.
                </li>
                <li>
                  You are responsible for reviewing and testing any AI-generated code before deploying
                  it to production.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. Public API</h2>
              <p className="mb-3">
                Our public JSON endpoints (<code className="text-white/60 font-mono text-xs">/api/prompts.json</code>,{" "}
                <code className="text-white/60 font-mono text-xs">/api/presets.json</code>) are provided
                freely for integration with bots, scripts, and other services.
              </p>
              <ul className="list-disc list-inside space-y-2 text-white/40">
                <li>These endpoints are provided &quot;as is&quot; with no uptime guarantees.</li>
                <li>We reserve the right to modify or discontinue the API at any time without notice.</li>
                <li>
                  Do not use the API in a manner that places excessive load on our infrastructure
                  (e.g., rapid automated polling). Cache responses where possible.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. Intellectual Property</h2>
              <p>
                The Promter name, logo, and website design are the property of their respective
                owners. The underlying prompt content and source code are open source under the MIT
                License. Third-party trademarks (e.g., ChatGPT, Claude, Cursor) belong to their
                respective owners.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. Disclaimer of Warranties</h2>
              <p>
                The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
                either express or implied. We do not guarantee that the Service will be uninterrupted,
                error-free, or that generated prompts will produce specific results with any AI tool.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, Promter and its contributors shall not be
                liable for any indirect, incidental, special, consequential, or punitive damages
                arising from your use of the Service, including but not limited to damages from
                AI-generated code, data loss, or service interruptions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">8. User Conduct</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-2 text-white/40 mt-2">
                <li>Use the Service for any unlawful purpose.</li>
                <li>Attempt to disrupt or interfere with the Service&apos;s infrastructure.</li>
                <li>Scrape or crawl the Service in a way that degrades performance for others.</li>
                <li>Misrepresent Promter&apos;s prompts as your own proprietary product.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">9. Changes to These Terms</h2>
              <p>
                We may update these Terms of Use at any time. Changes will be posted on this page with
                an updated date. Continued use of the Service after changes constitutes acceptance.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
              <p>
                For questions about these Terms of Use, please open an issue on our GitHub repository
                or contact us through the channels listed on the website.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
